FROM amazoncorretto:17.0.8-alpine3.18 as build
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN sed -i 's/\r$//' ./gradlew
RUN ./gradlew bootJar

FROM amazoncorretto:17.0.8-alpine3.18
WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/app.jar
CMD ["java", "-Xmx256m", "-Xms256m", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/dumps", "-XX:+PrintGCDetails", "-Xlog:gc*:file=/logs/gc.log:time:filesize=50M", "-jar", "/app/app.jar", "--spring.profiles.active=prod"]
EXPOSE 80
